url: jdbc:postgresql://host.docker.internal:5434/liquibase_db
username: postgres
password: 12345
driver: org.postgresql.Driver
changeLogFile:changelog/changelog.xml

# postgres docker comando del contenedor
#--------------------------------------------------
#  docker run --name postgres-liquibase -e POSTGRES_DB=liquibase_db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=12345 -p 5434:5432 -d postgres



# ejecutar changelog en powerShell
#--------------------------------------------------
# docker run --rm -v ${PWD}:/liquibase/changelog -v ${PWD}:/liquibase/classpath liquibase/liquibase --classpath=/liquibase/classpath/postgresql-42.7.10.jar --defaultsFile=/liquibase/changelog/liquibase.properties update




