url: jdbc:postgresql://host.docker.internal:5434/liquibase_db
username: postgres
password: 12345
driver: org.postgresql.Driver
changeLogFile: changelog.xml

# postgres docker comando del contenedor
#--------------------------------------------------
#  docker run --name postgres-liquibase -e POSTGRES_DB=liquibase_db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=12345 -p 5434:5432 -d postgres



